name: Deploy Astro Site to GitHub Pages

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '16 0 * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false
          
      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          check-latest: true
          cache: 'pnpm'
          cache-dependency-path: '.blog/pnpm-lock.yaml'

      # NOTE: `rehype-mermaid` depends on `playwright` with `chrome` browser
      - name: Install Playwright (with Chromium)
        run: |
          cd .blog
          pnpm dlx playwright install --with-deps chromium

      - name: Install dependencies, build, and export site
        uses: withastro/action@v3
        with:
          node-version: 22
          package-manager: pnpm
          path: .blog
          build-command: npm run build
          export-dir: dist
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages
          folder: .blog/dist
